In [1]:
import numpy as np

In [2]:
# List of functions explained 
function1 = np.vdot 
function2 = np.squeeze
function3 = np.ravel
function4 = np.bitwise_and
function5 = np.correlate

## Function 1 - np.vdot 

Vector Dot Product

In [3]:
# Example 1 - working (change this)
v1 = [1, 2]

v2 = [5, 6]

np.vdot(v1, v2)

17

In [4]:
# Example 2 - working
v1 = [1,2,3]
      
v2 = [4,5,6]
np.vdot(v1, v2)

32

vdot does dot product of two vectors of same dimension

In [5]:
# Example 3 - breaking (to illustrate when it breaks)
v1 = [1, 2]

v2 = [5, 6, 7]

np.vdot(v1, v2)

ValueError: ignored

It does vector dot product of two vectors with same dimension, not with different dimensions

It can be used only for vectors, Not for arrays and np.vdot is different from np.dot

## Function 2 - np.squeeze

Remove axes of length one from array

In [6]:
# Example 1 - working

x = np.array([[[1],[2],[4]]])
np.squeeze(x)


array([1, 2, 4])

In [7]:
# Example 2 - working

x = np.array([[[1],[2],[4]]])
np.squeeze(x, axis=0)

array([[1],
       [2],
       [4]])

It squeezes the given array to speicifed axis

In [8]:
# Example 3 - breaking (to illustrate when it breaks)

x = np.array([[[1],[2],[4]]])
np.squeeze(x, axis=1)

ValueError: ignored

It doesn't take axis = 1 to squeeze

squeeze() function is used when we want to remove single-dimensional entries from the shape of an array.

## Function 3 - np.ravel

Returns a contiguous flattened array

In [9]:
# Example 1 - working
x = np.array([[1, 2, 3], [4, 5, 6]])
np.ravel(x)

array([1, 2, 3, 4, 5, 6])

Gives a contiguous array

In [10]:
# Example 2 - working
x = np.array([[1, 2, 3], [55, 45, 6], [7,8,9]])
np.ravel(x)

array([ 1,  2,  3, 55, 45,  6,  7,  8,  9])

Gives a contiguous array 

In [11]:
# Example 3 - breaking (to illustrate when it breaks)
x = np.array([[1, 2, 3], [4, 5, 6]])
x.ravel(order='V')

ValueError: ignored

Ravel takes only C,F,A,K as order arguments. Any alphabet other than that is an error. 

It can be used when 2-d array or multi dimensional array needs to be converted to single 1-d array

## Function 4 - np.bitwise_and

Calculates the and operation on integers that are converted to binary and returns the result.

In [12]:
# Example 1 - working
a = np.array([[-1, 2], [3, 4]])
b = np.array([4,5])
np.bitwise_and(a,b)

array([[4, 0],
       [0, 4]])

Mathematical calculation of bitwise and of the given arrays. Converts the given numbers to binary and computes the and operation on binary numbers and returns the result.

In [13]:
# Example 2 - working
a = np.array([1])
b = np.array([4])
np.bitwise_and(a,b)


array([0])

In [14]:
# Example 3 - breaking (to illustrate when it breaks)
a = np.array([45])
b = np.array(['String'])
np.bitwise_and(a,b)


TypeError: ignored

Bitwise_and takes only integer values. It doesn't take other data types. In this one input is a string.

To check some logical operations in the code. To assign some flags based on certain conditions. We can check if the conditions are true by bitwise_and on integers. 

## Function 5 - np.correlate

Cross-correlation of two 1-dimensional sequences.

In [15]:
# Example 1 - working
np.correlate([1,2,3], [9,5,6])


array([37])

In [16]:
# Example 2 - working
np.correlate([1, 2, 3], [0, 10, 0.15], "same")

array([10.3 , 20.45, 30.  ])

In [17]:
# Example 3 - breaking (to illustrate when it breaks)
np.correlate([2,4,5], 3)

ValueError: ignored

np.correlate takes both the arguments as arrays. In the above example one of the argument is integer and not array.

Correlation is used to find the degree of dependence on two columns. More the correlation higher the dependence or importance.

## Conclusion

5 different functions out of many numpy functions are discussed and certain cases where these functions fail are also demonstrated.

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* Geeks for geeks numpy tutorial: https://www.geeksforgeeks.org/python-numpy/
